project:
  type: website

execute: 
  freeze: auto

website:
  title: "Home" # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: "EconMaett"
    # background: primary
    search: false
    left: 
      - text: "Blog"
        icon: feather
        href: blog/index.qmd
      - text: "Projects"
        icon: gear
        href: projects/index.qmd
    right:
      - text: "Talks"
        icon: megaphone
        href: talks.qmd
    tools:
      - icon: github
        href: https://github.com/EconMaett/econmaett.github.io

format:
  html:
    theme: [cosmo, styles.scss]
